apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-commanders-assignment-1
  namespace: argocd
spec:
  project: default
  source:
    directory:
      exclude: '{*.sh,README.md}'
      include: '*.yaml'
      recurse: true
    path: general_info/gitops-assignment/assignment-1/k8s
    repoURL: https://github.com/daasnigeria/daascohort3.git
    targetRevision: feature/pod-commanders/gitops-assignment
  destination:
    namespace: assignment-1
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      # Resource Management Options
      - CreateNamespace=true     # Auto-create namespace if it doesn't exist
      
