apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-commanders
  namespace: argocd
spec:
  project: default
  source:
    directory:
      exclude: '{*.sh,README.md}'
      include: '*.yaml'
      recurse: true
    path: argocd-example-apps/guestbook


    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: master
  destination:
    namespace: assignment-2
    name: second-cluster
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      # Resource Management Options
      - CreateNamespace=true     # Auto-create namespace if it doesn't exist
 