apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-app
  namespace: argocd
spec:
  project: default
  source:
    path: assignment-3/apps
    repoURL: https://github.com/malikhq/pod-commanders.git
    targetRevision: pod-commanders
  destination:
    namespace: assignment-3
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true        # Delete resources that exist in cluster but not in Git
      selfHeal: true     # Force sync when cluster state differs (even manual changes)
      allowEmpty: false  # Prevent sync with zero resources (safety check)
    syncOptions:
      # Resource Management Options
      - CreateNamespace=true     # Auto-create namespace if it doesn't exist
      - PrunePropagationPolicy=foreground  # Wait for dependent resources before deleting (foreground/background/orphan)
      - PruneLast=true          # Prune resources after new resources are healthy
      
      # Validation and Dry-Run Options
      - Validate=true           # Validate resources against Kubernetes API
      - ApplyOutOfSyncOnly=true # Only apply resources that are out-of-sync (efficiency)
      
      # Server-Side Apply Options 
      - ServerSideApply=true    # Use server-side apply instead of client-side
      - RespectIgnoreDifferences=true # Honor ignoreDifferences during sync
      
      # Resource Handling Options
      - FailOnSharedResource=false  # Don't fail if resource is managed by another app
      - Replace=false           # Use replace instead of apply (destructive)
      